tsuyoshicho/action-textlint

- Dockerfile
- entrypoint.sh
> fix: docker/entrypoint.sh

- Dockerfile
- package-lock.json
- package.json
> fix: depend

- Dockerfile
- README.md
- action.yml
- entrypoint.sh
Use version and npx controll project or default or defined version textlint.
> fix: textlint package install and execute

- entrypoint.sh
> feat: use npm ls

- .github/workflows/reviewdog.yml
- README.md
> docs: Update use checkout v2 and rule fix 'need package.json'

- README.md
Tagging to minor version for last v1 fixing.
> doc: Update README : add support version

- .github/workflows/reviewdog.yml
- README.md
- action.yml
- entrypoint.sh
> feat: npm v7 support for v2

- entrypoint.sh
> feat: diff support

- README.md
- action.yml
- entrypoint.sh
like eslint opt
and treat default
> feat: update config and script

- .github/workflows/reviewdog.yml
- README.md
fix setup-node version for regulars
> fix: setup-node for regular version

- Dockerfile
> ci: update image,apt cmd

- .github/renovate.json
- entrypoint.sh
> chore: fix misc

- .github/workflows/reviewdog.yml
Fix do not use hadolint entry error
> ci: hadolint comment out

- .github/workflows/release-check.yml
- .github/workflows/release.yml
> ci: update release(only PR verup)

- script.sh
> fix: script for exit code

- script.sh
latest https://github.com/reviewdog/action-suggester code apply
> fix: diff cleanup

- script.sh
related https://github.com/snow-actions/sandbox/pull/4
- github-pr-review 指定時に filter_mode が反映されていないこと
- 終了コードのハンドリングにも一部問題があること
- fail_on_error もあつかっていないこと
- なし
- ただしく filter_mode が作用し、さらに終了コード的な問題がない
https://github.com/tsuyoshicho/action-test-repo/pull/45
> fix: github-pr-preview reporter use user selected filter_mode

- script.sh
> fix: more fix textlint exicode (rel #426)

- .github/workflows/reviewdog.yml
> ci: fix version

- script.sh
> fix: miss exit code handling
